In [1]:
import numpy as np

In [5]:
l = [i for i in range(10)]
a = 0
while a <len(l):
    l.pop(a)
    a += 1
print(l)

[1, 3, 5, 7, 9]


In [11]:
a = np.array([[1,2], [3,4], [5,6], [7,8]])
b = a[:, np.newaxis, :] - a[np.newaxis, :, :]
print(b)
c = np.sum(b**2, axis=-1)
print(c)
overlap = c <=8
np.fill_diagonal(overlap, False)
print(overlap)

[[[ 0  0]
  [-2 -2]
  [-4 -4]
  [-6 -6]]

 [[ 2  2]
  [ 0  0]
  [-2 -2]
  [-4 -4]]

 [[ 4  4]
  [ 2  2]
  [ 0  0]
  [-2 -2]]

 [[ 6  6]
  [ 4  4]
  [ 2  2]
  [ 0  0]]]
[[ 0  8 32 72]
 [ 8  0  8 32]
 [32  8  0  8]
 [72 32  8  0]]
[[False  True False False]
 [ True False  True False]
 [False  True False  True]
 [False False  True False]]
